### ISSUE TITLE
About IoU

### ISSUE THREAD

**Issue by qqning** [e-lab/LinkNet#10]
Hi, @codeAC29  
I cannot obtain the high IoU in my training.
I looked into your code and found [that](https://github.com/e-lab/LinkNet/blob/8805ef7ea91f8cd77edf2897514fa85f21aa3c51/test.lua#L149), the `IoU` is computed via `averageValid `. But this is actually computing the mean of class accuracy. The IoU should be the value of `averageUnionValid `. 
Do you notice the difference and obtain 76% IoU by `averageUnionValid ` ?

Sorry for the trouble. For convenience, I refer the definition of `averageValid ` and `averageUnionValid ` [here](https://github.com/torch/optim/blob/656c42af1f996e4a5d6aae3b9aeac831ca162241/ConfusionMatrix.lua#L135-L136).

**Comment by AnzoChou** [comment]
@qqning After checking the [definition of metrics](https://www.cityscapes-dataset.com/benchmarks/#scene-labeling-task), I think you are right. The author may reported wrong numbers. The `mean IoU`(76.4%) in paper is actually the `mean class accuracy` and the `iIOU`(58.6%) is actually the `mean IoU`.

**Comment by codeAC29** [comment]
@qqning the displayed values after each epoch are incorrect. Thank you for pointing it out. We did not use `optim` to calculate the values reported in the paper; instead we modified [cityscapes script](https://github.com/mcordts/cityscapesScripts) to calculate IoU and iIoU since `optim` package does not give us iIoU values.
