### ISSUE TITLE
Fine Tuning

### ISSUE THREAD

**Issue by VanitarNordic** [e-lab/LinkNet#3]
Hi,

is there any possibility to fine-tune this model on a custom datase with different number of classes? The pre-trained weights must be exist also, as I know.

**Comment by codeAC29** [comment]
@VanitarNordic yes you can fine-tune your model or train it completely from scratch on any custom dataset. You will just have to write a data loader. One of the data loader located [here](https://github.com/e-lab/LinkNet/tree/master/data) can be used as an example.

**Comment by VanitarNordic** [comment]
Thank you. Two tips remains:

1) The pre-trained weights (CityScapes, CamVid) and where to load them
2) Where to change number of classes

**Comment by codeAC29** [comment]
1. Add a `model.lua` file similar to [this](https://github.com/e-lab/LinkNet/blob/master/models/model.lua) and load your pretrained model instead of defining all the layers.
2. Just modify your class list. For example modify [this line](https://github.com/e-lab/LinkNet/blob/master/data/loadCamVid.lua#L23) in case of camvid dataset.
